config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::prefix('api', function ($routes) {
    $routes->setExtensions(['json']);
    // $routes->resources('Users');
    $routes->fallbacks(DashedRoute::class);
});

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Users', 'action' => 'login']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    // $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/Post.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

class Post extends Entity
{

    protected $_accessible = [
        'parent_id' => true,
        'user_id' => true,
        'content' => true,
        'image_name' => true,
        'created' => true,
        'modified' => true,
        'deleted' => true
    ];
}

src/Model/Table/PostsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

class PostsTable extends Table
{
    /**
     * Initialize method
     *
     * @param  array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('posts');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Users')
            ->setForeignKey('user_id');

        $this->hasMany('PostLikes')
            ->setForeignKey('post_id');

        $this->hasMany('PostComments')
            ->setForeignKey('post_id');

        $this->hasMany('Reposts')
            ->setForeignKey('parent_id');

        $this->belongsTo('Reposts', ['className' => 'Posts'])
            ->setForeignKey('parent_id');
    }

    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('user_id')
            ->notEmptyString('user_id', 'Invalid action. Cannot access session user id.');

        $validator
            ->requirePresence('content')
            ->maxLength('content', 140)
            ->notEmptyString('content', 'Post content is required');


        $validator
            ->allowEmptyFile('image_name')
            ->add(
                'image_name', 'validExtension', [
                'rule' => ['extension', ['png', 'jpg', 'gif', 'jpeg']], 
                'message' => 'Please supply a valid image. 
                    Allowed extensions are only gif, jpeg, png and jpg.'
                ]
            );

        return $validator;
    }
}

src/Controller/Api/PostsController.php
<?php
namespace App\Controller\Api;

use Cake\Http\Exception\UnauthorizedException;
use Cake\Http\Exception\NotFoundException;
use Cake\Log\Log;
/**
 * Posts Controller
 *
 * @property \App\Model\Table\PostsTable $Posts
 */
class PostsController extends AppController
{

    public function initialize()
    {
        parent::initialize();
        $this->loadComponent('Paginator');
        $this->loadModel('Users');
        $this->loadModel('PostComments');
        $this->loadModel('PostLikes');
        $this->loadModel('Follows');
        $this->loadModel('Followers');
        $this->loadModel('Followings');
    }

    /**
     * Index method
     *
     * This method display the home page of the user after login. This also displays
     *  posts of the logged in user and the posts of the users he/she follows.
     *
     * @param int|null $userId User  id
     *
     * @return \Cake\Http\Response|null
     */
    public function getIndexContent(int $userId = null, int $sessUid = null)
    {
        $code = null;
        $message = null;

        $userDetail = $this->Users->find('all')
            ->where(
                [
                'activated' => 1,
                'id' => $userId
                ]
            )
            ->first();

        if (!$userDetail) {
            throw new NotFoundException(__('The requested user account is not available.'));
        }

        $followedThisUser = $this->checkFollowing($userId, $sessUid);
        $followers = $this->getFollower($userId, $sessUid);
        $followings = $this->getFollowing($userId, $sessUid);
        $followerCount = $this->getFollowerCount($userId);
        $followingCount = $this->getFollowingCount($userId);

        if ($userId == $sessUid) {
            $userIdArray = $this->getFollowedIds($userId);
        }

        $userIdArray[] = $userId;
        
        $this->paginate = [
            'contain' => ['Users', 'Reposts.Users'],
            'conditions' => [
                'Posts.user_id IN' => $userIdArray,
                'Posts.deleted' => 0,
            ],
            'limit' => 10,
            'order' => ['Posts.created' => 'desc']  
        ];
        $posts = $this->paginate();
        $comments = $this->getPostComments($posts, $sessUid);
        $paging = $this->request->getParam('paging');

        $data = [
            'followers' => $followers,
            'followings' => $followings,
            'followerCount' => $followerCount,
            'followingCount' => $followingCount,
            'followedThisUser' => $followedThisUser,
            'userDetail' => $userDetail,
            'comments' => $comments,
            'posts' => $posts,
            'paging' => $paging
        ];

        $code = $this->codeSuccessCreate201;
        $message = 'OK';

        $this->set(compact('code', 'message', 'data'));
        $this->set('_serialize', ['code', 'message', 'data']);

    }

    /**
     * Get PostComments method
     *
     * This method fetches and builds each post's comments.
     *
     * @param object $posts User's posts dataset
     *
     * @return array
     */
    private function getPostComments(object $posts, int $sessUid) : array
    {
        $comments = [];
        foreach ($posts as $key => $post) {
            $postId = $post['id'];

            $comments[$key]['comments'] = $this->PostComments->find()
                ->where(
                    [
                    'PostComments.post_id' => $postId,
                    'PostComments.deleted' => 0
                    ]
                )
                ->contain('Users')
                ->toArray();
            $comments[$key]['commentCount'] = $this->PostComments->find()
                ->where(
                    [
                    'post_id' => $postId,
                    'deleted' => 0
                    ]
                )
                ->count();

            $comments[$key]['likeCount'] = $this->PostLikes->find()
                ->where(['post_id' => $postId])
                ->count();

            $result = $this->PostLikes->findByPost_idAndUser_id($postId, $sessUid)
                ->first();
            $comments[$key]['userLiked'] = ($result) ? true : false;

        }

        return $comments;
    }

    /**
     * Get Followed Id's method
     *
     * This method fetches all id's of the user followed accounts.
     *
     * @param in $userId User id
     *
     * @return array
     */
    private function getFollowedIds(int $userId) : array
    {
        $query = $this->Follows->find(
            'list', [
                'keyField' => 'id',
                'valueField' => 'followed_id'
            ]
        )
            ->where(['follower_id' => $userId])
            ->toArray();

        return $query;
    }

    /**
     * Check Following method
     *
     * This method checks if the viewed user has been followed by the currently logged in user.
     *
     * @param int $userId  User id
     * @param int $sessUid User id of the currently logged in account
     *
     * @return bool
     */
    private function checkFollowing(int $userId, int $sessUid) : bool
    {

        $query = $this->Follows->findAllByFollowed_idAndFollower_id($userId, $sessUid);
        $result = $query->toArray();

        $return = ($result) ? true : false;

        return $return;
    }

    /**
     * Get Follower method
     *
     * This method returns the user's list of followers.
     *
     * @param int $userId  User id
     * @param int $sessUid User id of the currently logged in account
     *
     * @return array
     */
    private function getFollower(int $userId, int $sessUid) : array
    {
        $query = $this->Followers->find()
            ->distinct(['Followers.id','UserFollowing.id'])
            ->where(['Followers.followed_id' => $userId])
            ->contain('Users.UserFollowing')
            ->limit(10)
            ->toArray();

        return $query;
    }

    /**
     * Get Following method
     *
     * This method returns the user's list of followed user accounts.
     *
     * @param int $userId  User id
     * @param int $sessUid User id of the currently logged in account
     *
     * @return array
     */
    private function getFollowing(int $userId, int $sessUid) : array
    {
        $query = $this->Followings->find()
            ->distinct(['Followings.id', 'UserFollowing.id'])
            ->where(['Followings.follower_id' => $userId])
            ->contain('Users.UserFollowing')
            ->limit(10)
            ->toArray();

        return $query;
    }

    /**
     * Get Follower Count method
     *
     * This method returns the user's total number of followers.
     *
     * @param int $userId User id
     *
     * @return int
     */
    private function getFollowerCount(int $userId) : int
    {
        $query = $this->Followers->find()
            ->where(['followed_id' => $userId])
            ->count();

        return $query;
    }

    /**
     * Get Following Count method
     *
     * This method returns the user's total number of followed user accounts.
     *
     * @param int $userId User id
     *
     * @return int
     */
    private function getFollowingCount(int $userId) : int
    {
        $query = $this->Followings->find()
            ->where(['follower_id' => $userId])
            ->count();

        return $query;
    }

    /**
     * Add method
     *
     * @return Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $this->request->allowMethod(['post', 'put']);

        $code = null;
        $message = null;
        $data = $this->request->getData();

        if (isset($data['postAttachment'])) {
            $img = $data['postAttachment']['value'];
            $img = explode(',', $img);
            $imageFile = base64_decode($img[1]);

            $extn = substr(
                    $data['postAttachment']['filename'], 
                    strrpos($data['postAttachment']['filename'], '.')+1
                );

            $fileName = "user_" . $data['user_id'] . "_" . date('His') .  "." . $extn;

            $file_dir = WWW_ROOT . 'img/posts/' . $fileName;
            file_put_contents($file_dir, $imageFile);

            $data['image_name'] = $fileName;
        }

        $post = $this->Posts->newEntity($data);

        if ($this->Posts->save($post)) {
            $code = $this->codeSuccessCreate201;
            $message = 'The post has been saved.';
        } else {
            $code = $this->codeInvalid400;
            $message = $this->renderErrors($post->getErrors());
        }

        $data = [];

        $this->set(compact('code', 'message', 'data'));
        $this->set('_serialize', ['code', 'message', 'data']);
    }


    /**
     * Edit method
     *
     * @param  int $data['id'] Post id.
     * @return Redirects on successful edit, renders error view otherwise.
     * @throws NotFoundException When record not found.
     */
    public function edit()
    {
        $this->request->allowMethod(['post', 'put', 'patch']);

        $code = null;
        $message = null;
        $data = $this->request->getData();
        $post = $this->Posts->get($data['id']);
        
        if (!$post) {
            throw new NotFoundException(__('Invalid action.'));
        }

        $data['image_name'] = isset($data['image_name']) ? $data['image_name'] : null;

        if (isset($data['postAttachment'])) {
            $img = $data['postAttachment']['value'];
            $img = explode(',', $img);
            $imageFile = base64_decode($img[1]);

            $extn = substr(
                    $data['postAttachment']['filename'], 
                    strrpos($data['postAttachment']['filename'], '.')+1
                );

            $fileName = "user_" . $data['user_id'] . "_" . date('His') .  "." . $extn;

            $file_dir = WWW_ROOT . 'img/posts/' . $fileName;
            file_put_contents($file_dir, $imageFile);

src/Template/Posts/index.ctp
<?php 
    $userDetail = json_decode(json_encode($userDetail)); 
    $followings = json_decode(json_encode($followings)); 
    $followers = json_decode(json_encode($followers)); 
?>
<div class="row p-5">
    <div class="col-sm-12 col-lg-5 ">
        <!-- PROFILE -->
        <div class="container shadow-lg bg-transparent">
            <div class="card bg-transparent border-0 pt-4">
                <?php 
                    if ($userDetail->profile_picture) {
                        $myProfile = $userDetail->profile_picture;
                    } else {
                        $myProfile = 'default-profile.png';
                    }
                ?>
              <?= $this->Html->image(
                            'profiles/'.$myProfile, 
                            ['alt' => '',
                                'class' => 'rounded-circle align-self-center border border-white',
                                'width' => '125',
                                'height' => '125'
                            ]
                        ) ?>
              <div class="card-body text-center pt-2">
                <span class="font-italic text-muted">@<?= $userDetail->username ?></span>
                <h5 class="card-title font-weight-bold">
                    <?= $userDetail->first_name ?>
                    <?= $userDetail->last_name ?>
                </h5>
                <?php if($editAccess == false): ?>
                    <?php 
                        if($followedThisUser) {
                            $followLabel = 'Unfollow';
                            $followClass = 'btn-secondary';
                        } else {
                            $followLabel = 'Follow';
                            $followClass = 'btn-outline-secondary';
                        }
                    ?>
                <?= $this->Form->postButton(
                                $followLabel,
                                ['controller' => 'follows', 
                                    'action' => 'follow',
                                    $userDetail->id
                                ],
                                ['class' => "btn {$followClass} btn-sm px-5"]
                            ) ?>
                <?php endif ?>
              </div>
            </div>
        </div>
        <!-- FOLLOWING / FOLLOWERS -->
        <div class="container shadow-lg bg-transparent mt-2 py-2">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link text-dark border active" data-toggle="tab" href="#following">
                        Following
                        <span class="badge badge-secondary ml-2"><?= $followingCount ?></span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark border" data-toggle="tab" href="#follower">
                        Followers
                        <span class="badge badge-secondary ml-2"><?= $followerCount ?></span>
                    </a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane container active p-0" id="following">
                    <?php $followingParams = [
                        'followings' => $followings,
                        'followingCount' => $followingCount,
                        'editAccess' => $editAccess
                    ] ?>
                    <?= $this->element('posts/following_view',$followingParams) ?>
                </div>
                <div class="tab-pane container fade p-0" id="follower">
                    <?php $followerParams = [
                        'followers' => $followers,
                        'followerCount' => $followerCount,
                        'editAccess' => $editAccess
                    ] ?>
                    <?= $this->element('posts/follower_view',$followerParams) ?>
                </div>
            </div>
        </div>
    </div>
    <!-- CREATE POST -->
    <div class="col-sm-12 col-lg-7">
        <div class="container shadow-lg bg-transparent p-3 mb-2 <?= $hideAccess ?>">
            <?= $this->Form->create('Posts', [
                'enctype'=>'multipart/form-data',
                'novalidate' => true,
                'url' => array('controller' => 'posts', 'action' => 'add')
            ]) ?>
                <div class="form-group">
                    <?=  $this->Form->control('content', [
                        'label' => 'Create Post',
                        'rows' => '4',
                        'class' => 'form-control'
                    ]) ?>
                </div>
                <div class="custom-file w-50">
                   <?=  $this->Form->file('image_name', [
                        'class' => 'custom-file-input',
                        'id' => 'post-attachment'
                    ]) ?>
                    <label class="custom-file-label text-truncate" for="post-attachment">
                        Choose image
                    </label>
                    <?php
                    if ($this->Form->isFieldError('image_name')) {
                        echo $this->Form->error('image_name');
                    }
                    ?>
                </div>
                <div class="float-right">
                    <?= $this->Form->button( 'Post', [
                        'class' => 'btn btn-outline-primary'
                    ]) ?>
                </div>
            <?= $this->Form->end() ?>
        </div>
        <!-- RECENT POST BOARD -->
        <div class="container shadow-lg bg-transparent p-3">
            <h5>Recent Posts</h5>
            <hr>
            <?php if ($posts): ?>
            <?php foreach ($posts as $key => $post): ?>
            <?php $post = json_decode(json_encode($post)); ?>
            <div class="card mb-3">
                <?= $this->element('posts/post_view',['post' => $post]) ?>
                <!-- REPOST CONTAINER -->
                <?php if(isset($post->repost->id)): ?>
                <?= $this->element('posts/repost_view',['post' => $post]) ?>
                <?php endif ?>
                <?= $this->element('posts/comments',[
                    'comment' => $comments[$key],
                    'post' => $post
                ]) ?>
            </div>
            <?php endforeach ?>
            <?= $this->element('common/pagination',['pagination' => $pagination]) ?>
            <?php else: ?>
                <div class="card">
                    <div class="card-body text-center">
                        No available post yet.
                    </div>
                </div>
            <?php endif ?>
        </div>
    </div>
</div>

<!-- MODALS -->
<?= $this->element('posts/edit_post') ?>
<?= $this->element('posts/repost') ?>
<?= $this->element('posts/edit_comment') ?>
<?= $this->Html->script('post') ?>